ban:
    path:     /
    defaults: { _controller: "PidevReaBundle:Ban:index" }

ban_show:
    path:     /{id}/show
    defaults: { _controller: "PidevReaBundle:Ban:show" }

ban_new:
    path:     /new
    defaults: { _controller: "PidevReaBundle:Ban:new" }

ban_create:
    path:     /create
    defaults: { _controller: "PidevReaBundle:Ban:create" }
    requirements: { _method: post }

ban_edit:
    path:     /{id}/edit
    defaults: { _controller: "PidevReaBundle:Ban:edit" }

ban_update:
    path:     /{id}/update
    defaults: { _controller: "PidevReaBundle:Ban:update" }
    requirements: { _method: post|put }

ban_delete:
    path:     /{id}/delete
    defaults: { _controller: "PidevReaBundle:Ban:delete" }
    requirements: { _method: post|delete }
