rapportprorpriete:
    path:     /
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:index" }

rapportprorpriete_show:
    path:     /{id}/show
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:show" }

rapportprorpriete_new:
    path:     /new
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:new" }

rapportprorpriete_create:
    path:     /create
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:create" }
    requirements: { _method: post }

rapportprorpriete_edit:
    path:     /{id}/edit
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:edit" }

rapportprorpriete_update:
    path:     /{id}/update
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:update" }
    requirements: { _method: post|put }

rapportprorpriete_delete:
    path:     /{id}/delete
    defaults: { _controller: "PidevReaBundle:Rapportprorpriete:delete" }
    requirements: { _method: post|delete }
