agenceZone:
    path:     /agenceZone
    defaults: { _controller: PidevReaBundle:Stat:agenceZone }
nbrInscritMois:
    path:     /nbrInscritMois
    defaults: { _controller: PidevReaBundle:Stat:nbrInscritMois }
nbrOffreClientAgence:
    path:     /nbrOffreClientAgence/{id}
    defaults: { _controller: PidevReaBundle:Stat:nbrOffreClientAgence }
nbrOffreAgence:
    path:     /offreAgence/{id}
    defaults: { _controller: PidevReaBundle:Stat:offreAgence }
